### ISSUE TITLE
Add responsiveness on mobile 

### ISSUE THREAD

**Issue by harshitkathuria** [harshitkathuria/InternDigger#2]

**Comment by Kirill-frontend** [comment]
I can do it.

**Comment by Kirill-frontend** [comment]
I got an error when starting the server
![image](https://user-images.githubusercontent.com/69352064/105254348-086e6880-5b8a-11eb-8971-5b400a2a1d9d.png)

**Comment by harshitkathuria** [comment]
Server starts with the database password (which is private). There is no need to start server for this. The folder you are looking for is: `project-directory -> views`. It contains all the pages. And the css and other styling is in: `project-directory -> public -> css` :)
